BaseExceptions are handled in ``saferepr``, which includes ``pytest.fail.Exception`` etc.
